### ISSUE TITLE
Narrow task boundaries sometimes cause the tasks to be merged

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm-splitter#38] opened 2024-07-04 22:59 UTC
**Describe the bug**

Example from Freetown:

![image](https://github.com/hotosm/fmtm-splitter/assets/78538841/b3965a2f-f263-4913-8735-aba36242fac7)

AOI:
[2024-07-03_Kroo_Bay_AOI-noZ.geojson.txt](https://github.com/user-attachments/files/16103281/2024-07-03_Kroo_Bay_AOI-noZ.geojson.txt)
Data extract:
[Data_Extract.geojson.txt](https://github.com/user-attachments/files/16103280/Data_Extract.geojson.txt)

- Generates a huge task with too many features - it looks like it should have been three.

**Expected behavior**

- Generate three separate tasks - debug why this did not happen.

**Comment by manjitapandey** [comment] 2024-10-29 10:44
Couldn't reproduce the behavior you mentioned. I tried using multiple avg feature count ranging from 40-70 features per tasks but the tasks doesn't seem to get merged. The chances could be i used different avg feature count or the issue has been resolved. 
@spwoodcock , If you could recall the number of feature you had an issue with, it would help me replicate. Otherwise we can close the issue as not reproducible for now and can reopen if faced again.

**Comment by spwoodcock** [comment] 2024-10-29 15:48
I was probably using a much lower feature count, say 15-30 range.

But I agree, if we can't reproduce this and it was a one off strange behaviour, then this can be closed 👍

**Comment by manjitapandey** [comment] 2024-10-30 08:57
No luck while testing with 15, 20 and 30 feature count too. So closing this issue for now.

**Closed by manjitapandey** 2024-10-30 08:57 UTC
Labels: bug, priority:high, effort:medium
